### ISSUE TITLE
请问这个java项目怎么运行啊

### ISSUE THREAD

**Issue by renkeEdogawa** [AFoolLove/MetalMaxRe#3]
我把代码拉到了本地，但是windows下双击gradlew.bat，却只是command界面一闪而过，也没有出现那种我可以编辑的用户界面。。还是我的理解有问题，不会java，我只懂点C++，实在是一头雾水

**Comment by AFoolLove** [comment]
就是API，没有可视化界面，要修改什么需要你自己手动去调用相关方法
